// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqsiWYpFfRxhi4zINkfdIFeydbD7OhycU',
    appId: '1:165055643058:web:77b48e5b82ab713b17f8ab',
    messagingSenderId: '165055643058',
    projectId: 'formdemo-ae6c2',
    authDomain: 'formdemo-ae6c2.firebaseapp.com',
    storageBucket: 'formdemo-ae6c2.appspot.com',
    measurementId: 'G-THH0GN8QKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEOvS91txsSawJFelxDEIWs0OcsY40jiI',
    appId: '1:165055643058:android:4f556988f87ea89c17f8ab',
    messagingSenderId: '165055643058',
    projectId: 'formdemo-ae6c2',
    storageBucket: 'formdemo-ae6c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpsAXje5yFACu8lNaY97vlYbJLtcmm__E',
    appId: '1:165055643058:ios:4e3afad5ae02444517f8ab',
    messagingSenderId: '165055643058',
    projectId: 'formdemo-ae6c2',
    storageBucket: 'formdemo-ae6c2.appspot.com',
    iosBundleId: 'com.example.formDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpsAXje5yFACu8lNaY97vlYbJLtcmm__E',
    appId: '1:165055643058:ios:01c7a4eaf07d87bd17f8ab',
    messagingSenderId: '165055643058',
    projectId: 'formdemo-ae6c2',
    storageBucket: 'formdemo-ae6c2.appspot.com',
    iosBundleId: 'com.example.formDemo.RunnerTests',
  );
}
